document.write(' <nav class="navbar navbar-expand-lg navbar-light bg-primary" style="font-weight: bold;">');
document.write('<a class="navbar-brand" width="30" height="30" alt=""><img src="imgPagina/logo.png"></a>');
document.write('<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">');
document.write(' <span class="navbar-toggler-icon"></span>');
document.write('</button>');
document.write('<div class="collapse navbar-collapse" id="navbarSupportedContent">');
document.write(' <ul class="navbar-nav mr-auto">');
document.write('</ul>');
document.write('<form class="form-inline my-2 my-lg-0">');
document.write('<button class="btn btn-outline-light my-2 my-sm-0" type="submit" onclick="teste()">Cancelar Pedido</button>');
document.write('</form>');
document.write('</div>');
document.write('</nav>');
