document.write(' <nav class="navbar navbar-expand-lg navbar-light bg-primary" style="font-weight: bold;">');
document.write('<a class="navbar-brand" width="30" height="30" alt="" href="menuPrincipal.jsp"><img src="imgPagina/logo.png"></a>');
document.write('<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">');
document.write(' <span class="navbar-toggler-icon"></span>');
document.write('</button>');
document.write(' <div class="collapse navbar-collapse" id="navbarSupportedContent">');
document.write(' <ul class="navbar-nav mr-auto">     ');
document.write('<li class="nav-item dropdown">');
document.write(' <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">');
document.write('Produtos');
document.write('</a>');
document.write(' <div class="dropdown-menu" aria-labelledby="navbarDropdown">');
document.write(' <a class="dropdown-item" href="incluirProduto.jsp?status=0">Cadastrar Produtos</a>');
document.write(' <a class="dropdown-item" href="consultarProduto.jsp ">Consultar Produtos</a>');
document.write('</div>');
document.write(' </li>');
document.write(' <li class="nav-item dropdown">');
document.write('                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">');
document.write('Pedidos');
document.write('</a>');
document.write('<div class="dropdown-menu" aria-labelledby="navbarDropdown">');
document.write('  <a class="dropdown-item" href="consultarGrid.jsp">Pedidos Pendentes</a>');
document.write(' </div>');
document.write('</li>');
document.write('</ul>');
document.write(' <form class="form-inline my-2 my-lg-0">');
document.write(' <a class="btn btn-outline-light my-2 my-sm-0" href="alterarSenha.jsp">Alterar Senha</a>');
document.write(' <a class="btn btn-outline-light my-2 my-sm-0" href="logout.jsp">Sair</a>');
document.write('</form>');
document.write('</div>');
document.write('</nav>');